name: Deploy Curso Folder to GitHub Pages

on:
  push:
    branches:
      - main  # Ou o branch de sua escolha

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Verify the repository content
      run: |
        echo "Listing the repository content..."
        ls -la  # Lista os arquivos e pastas do repositório para verificar se 'curso' está lá

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create gh-pages branch
      run: |
        git checkout --orphan gh-pages  # Cria a branch gh-pages
        git reset --hard  # Reseta a branch
        git clean -fdx  # Limpa qualquer resquício de arquivos

    - name: Deploy to GitHub Pages
      run: |
        echo "Copying the 'curso' folder content to the root"
        cp -R ./curso/* ./  # Copia o conteúdo de 'curso' para o diretório atual
        cp -R ./curso/.* ./  # Copia arquivos ocultos da pasta 'curso' (se existirem)
        git add -A
        git commit -m "Deploy curso folder to GitHub Pages"
        git push --force origin gh-pages  # Faz o push para a branch gh-pages
