name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Quando houver um push para o branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # A branch de destino
          folder: curso     # A pasta onde estão os arquivos (pasta 'curso' no seu caso)
          token: ${{ secrets.GITHUB_TOKEN }}  # Usando o token do GitHub Actions
